export async function GET() {

    const data = {
        "messageCode": null,
        "messageDesc": null,
        "data": [
            {
                "id": "2400000484",
                "poNo": "POP2410187",
                "matCd": "YA84200017",
                "qtyOrd": 2,
                "tdqtySupld": 2,
                "tdqtySupldTemp": 2,
                "sinvNo": "05860351",
                "invDt": 1696006800000,
                "lotNo": null,
                "itemTotal": 1838,
                "itemQty": 2,
                "remainQty": 0,
                "itemNumber": null,
                "supCd": "0254",
                "supplierName": "LINDE (THAILAND) PUBLIC COMPANY LIMITED",
                "trnDt": 1696029444000,
                "invNo": "INV230000001",
                "invoiced": "Y",
                "matType": "2",
                "invUpd": "N",
                "spotCont": "C",
                "srcTyp": "M",
                "matModel": "-",
                "matSpec": "7M3(OLD 6M3)",
                "reqNo": "PRP12422614",
                "matName": "ARGON GAS",
                "kanbanNo": "84200017NP2300001",
                "status": "C",
                "ncFlag": "N",
                "cmpyCd": "T",
                "plantCd": "P",
                "giConv": "1",
                "unitPrice": 919,
                "whCd": "W05",
                "delPlace": "W05",
                "kgPersheet": 1,
                "isinteger": "Y",
                "uomDesc": "CYLINDER",
                "invTyp": "N",
                "plantName": null,
                "supBranchCd": "00006",
                "supBranchName": null,
                "matStoreType": null,
                "md": 1717756820000,
                "kanbanType": "N",
                "ccCharge": null,
                "wbsElement": null,
                "isReplace": false,
                "buom": "CYL"
            },
            {
                "id": "2400000485",
                "poNo": "POP2410187",
                "matCd": "YA84200017",
                "qtyOrd": 2,
                "tdqtySupld": 2,
                "tdqtySupldTemp": 2,
                "sinvNo": "05860351",
                "invDt": 1696006800000,
                "lotNo": null,
                "itemTotal": 1838,
                "itemQty": 2,
                "remainQty": 0,
                "itemNumber": null,
                "supCd": "0254",
                "supplierName": "LINDE (THAILAND) PUBLIC COMPANY LIMITED",
                "trnDt": 1696029444000,
                "invNo": "INV230000001",
                "invoiced": "Y",
                "matType": "2",
                "invUpd": "N",
                "spotCont": "C",
                "srcTyp": "M",
                "matModel": "-",
                "matSpec": "7M3(OLD 6M3)",
                "reqNo": "PRP12422614",
                "matName": "ARGON GAS",
                "kanbanNo": "84200017NP2300001",
                "status": "C",
                "ncFlag": "N",
                "cmpyCd": "T",
                "plantCd": "P",
                "giConv": "1",
                "unitPrice": 919,
                "whCd": "W05",
                "delPlace": "W05",
                "kgPersheet": 1,
                "isinteger": "Y",
                "uomDesc": "CYLINDER",
                "invTyp": "N",
                "plantName": null,
                "supBranchCd": "00006",
                "supBranchName": null,
                "matStoreType": null,
                "md": 1717756820000,
                "kanbanType": "N",
                "ccCharge": null,
                "wbsElement": null,
                "isReplace": false,
                "buom": "CYL"
            }
        ]
    }

    return Response.json(data
    )
}